services:
  - type: web
    name: sports-betting-backend
    env: node
    plan: free
    buildCommand: npm install && cd backend && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
